### ISSUE TITLE
Allow to pass datatase password as a secret

### ISSUE THREAD

**Issue by MohamedTalhaoui** [goharbor/harbor-helm#1214]
As of now, the DB password can only be passed on plain text in the value file, which is not secure.
Please allow to pass it as an existing secret.

**Comment by zyyw** [comment]
Hi @MohamedTalhaoui , we have a PR from the community that dealing with this issue:
https://github.com/goharbor/harbor-helm/pull/1179

**Comment by viceice** [comment]
the pre-upgrade job is missing the postgresql password from secret

**Comment by MohamedTalhaoui** [comment]
Hi,
I am using database.external.existing secret to reference the k8s secret holding my external DB password.
I am using Chart version 1.10.2.
This is working well with the core DB, however the value is not used for the Notary server and signer DBs.
The Notary deployments are using this secret 
https://github.com/goharbor/harbor-helm/blob/master/templates/notary/notary-secret.yaml
Which is relying on templates using clear text password from the values file:
https://github.com/goharbor/harbor-helm/blob/master/templates/_helpers.tpl#L90

It would be better to adapt the helm chart to also use the existing k8s secrets for Notary DBs password.

**Comment by Zboubinours** [comment]
I'm facing the same issue @MohamedTalhaoui is facing.

I'm using a k8s secret to securely provide my postgresql database password to harbor chart.
The core database (`database.external.coreDatabase`) is using the password I've put in the `database.external.existingSecret` k8s secret.

However, the `notary_signer` and `notary_server` databases are not using the password from the k8s secret.
They're using the password from `database.external.password` in the values.yaml file.

The [PR](https://github.com/goharbor/harbor-helm/pull/1179) you were talking about @zyyw did fix the issue for the coreDatabase, but not for the notary databases.

https://github.com/goharbor/harbor-helm/blob/master/templates/_helpers.tpl#L138

```tpl
{{- define "harbor.database.notaryServer" -}}
postgres://{{ template "harbor.database.username" . }}:{{ template "harbor.database.escapedRawPassword" . }}@{{ template "harbor.database.host" . }}:{{ template "harbor.database.port" . }}/{{ template "harbor.database.notaryServerDatabase" . }}?sslmode={{ template "harbor.database.sslmode" . }}
{{- end -}}
```

`{{ template "harbor.database.escapedRawPassword" . }}` contains the `database.external.password` value instead of the one in the `existingSecret` k8s secret.

**Comment by amgonzalezf** [comment]
What about allowing to set the initial password of the admin user ("posgres") of the database by using an existing secret instead of specifying the password in plain text in the values.yaml file when .database.type=internal? Right now, it's only possible if .database.type=external.

**Comment by viceice** [comment]
please re-open. it's still an issue!
