### ISSUE TITLE
To define ports.containerPort in notary-server helps some situations

### ISSUE THREAD

**Issue by sshota0809** [goharbor/harbor-helm#1234]
Hi, first of all thank you for developing the harbor-helm. It's so useful for me!

# My Proposal
At this time `ports.containerPort` is not defined in Deployment of notary-server
https://github.com/goharbor/harbor-helm/blob/5bfb951a22c325837dda4fe4264c8df00cd25636/templates/notary/notary-server.yaml

On the other hand, in some situations it makes things better so I think it should be defined.

e.g. In case of GKE, ingress is able to automatically detect health check path.
https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#health_checks

```
Note: containerPort field must be defined under pod spec and targetPort field must be defined under service spec for health check to infer parameters defined under readiness probe. If they are not defined, the health check for the backend service defaults to "/" path even if parameters are defined under readiness probe.
```

I'm going to make a PR, please wait a while.

**Comment by zyyw** [comment]
Hi @sshota0809 , thanks for trying harbor via harbor-helm and thank you for contributing harbor-helm by submitting a PR. 

Since Notary is going to be deprecated and harbor users are encouraged to use cosign (harbor 2.5.x / harbor-helm 1.9.x) for image signing activity, I'm afraid we may not introduce any more additional features/changes regarding Notary.

**Comment by sshota0809** [comment]
@zyyw 
Thank you for your reply. I didn't know that but it totally makes sence that a new feature about notary isn't added amymore.

I'll close this issue.
