### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by drew-viles** [goharbor/harbor-helm#1563]
I'm trying to make use of some of the features that live in master but they seem to be getting missed in the releases being created.

For example, [this snippet](https://github.com/goharbor/harbor-helm/blob/master/templates/core/core-dpl.yaml#L133-L135) was added 4 months ago but failed to make any of the releases since.

Is there a reason for this as I'd like to add the CONFiG_OVERWRITE_JSON env var as [described here](https://goharbor.io/docs/2.8.0/install-config/configure-system-settings-cli/#set-configuration-items-using-an-environment-variable).

Are the releases not created from the "current" master state?

**Comment by lion7** [comment]
Same problem here. Already waiting since mid-June until the `CONFIG_OVERWRITE_JSON` is actually present in 1 of the releases. It seems that new releases get created from a different base or idk?

@zyyw shamelessly pinging since you created the last release 😇

**Comment by zyyw** [comment]
Hi @drew-viles @lion7 this `CONFIG_OVERWRITE_JSON` feature is merged in master via this PR:
* https://github.com/goharbor/harbor-helm/pull/1468

It will be available in the next minor release, say 1.13.0. The next release created from the current master branch are minor releases. The reason why we haven't made a minor release 1.13.0 yet is because harbor-helm is trying to align with the release schedule with [harbor-oss](https://github.com/goharbor/harbor) project, which means harbor-helm make a minor release or patch release after there is a corresponding minor release in harbor-oss project. Harbor-helm next release 1.13.0 from master is for harbor-oss v2.9.0. Currently harbor-oss v2.9.0 is in RC stage. It should be GA-ed in the near feature. After harbor-oss v2.9.0 is release, harbor-helm will release 1.13.0 at once.
