### ISSUE TITLE
`existingSecret` broken for notary using external database and `registry.credentials`

### ISSUE THREAD

**Issue by nusnewob** [goharbor/harbor-helm#1574]
* Predefined `existingSecret` is completely ignored for generated `harbor-notary-server` secret, cause notary server and signer failing to connect external database.

	https://github.com/goharbor/harbor-helm/blob/v1.12.4/templates/_helpers.tpl#L138-L144
	https://github.com/goharbor/harbor-helm/blob/v1.12.4/templates/_helpers.tpl#L90-L100

* Similarly `existingSecret` is also broken for `registry.credentials`

	https://github.com/goharbor/harbor-helm/blob/v1.12.4/templates/registry/registry-secret.yaml#L9

**Comment by zyyw** [comment]
Hi @nusnewob, since `harbor-notary-server` is removed in Harbor oss v2.9.0, the support for notary related topic will be limited.

> Similarly `existingSecret` is also broken for `registry.credentials`
The url you provided is https://github.com/goharbor/harbor-helm/blob/v1.12.4/templates/registry/registry-secret.yaml#L9, which is not about `existingSecret`, I'm assuming you actually want to discuss this: https://github.com/goharbor/harbor-helm/blob/v1.12.4/values.yaml#L583
Would you please elaborate how is it broken? Or alternatively, would you mind submit a PR for the broken scenario you have  observed.
