### ISSUE TITLE
Misbehaviour during upgrade

### ISSUE THREAD

**Issue by barsa-net** [goharbor/harbor-helm#1674]
When using the internal database, during an upgrade from a previous Chart version, `POSTGRES_PASSWORD` gets replaced with `illegal base64 data at input byte 3` this is caused by a075633 and specifically by line 101:

`{{- .Values.database.internal.password | default (index $existingSecret.data "POSTGRES_PASSWORD") | b64dec -}}`

that causes an attempt to decode `.Values.database.internal.password` (which is in fact already plain text) instead of decoding only the existing secret value like this

`{{- .Values.database.internal.password | default (index $existingSecret.data "POSTGRES_PASSWORD" | b64dec) -}}`

**Comment by mstavrev** [comment]
I believe I've tripped that  issue. Is there a work-around? I had a Harbor v1.13.0 and upgrade it to v1.14.0 via helm.
Naturally, I am using persistent storage. Currently it does not work, even if I downgrade it to v1.13.0.

**Comment by barsa-net** [comment]
Assuming that you have your correct password set in your `.Values.database.internal.password`, my best guess to make it work and keeping v1.14.0 is to manually delete `harbor-database` secret before attempting an `helm upgrade` command, that should skip the issue entirely; that's because the Chart attempt a lookup of the existing secret.

You can confirm the correct value is being used by using `--dry-run=server` option e.g. `helm upgrade harbor harbor/harbor --version 1.14.0 --dry-run=server -f values.yaml`

Note: `--dry-run` and `--dry-run=server` have different results in that case, you should use the latter.

**Comment by mstavrev** [comment]
Thanks for the feedback. The removal of harbor-database secret did the trick. I've actually never setup an explicit password for the harbor database instance, so it had always be using the default one "changeit" 🤫. All good now.

**Comment by ywk253100** [comment]
Reopen it for patches

**Comment by mwhcp** [comment]
Just one question:  I have also updated from OSS harbor 2.9.1/helm 1.13.1 to 2.10.0/helm 1.14.0. In our _development environment_  we are currently using the **internal database** and during the upgrade the deployments harbor-core and harbor-exporter failed.  

**Root cause:**  manifest value in `harbor-core` (POSTGRESQL_PASSWORD) and `harbor-exporter` (HARBOR_DATABASE_PASSWORD)  are not (as expected) base64 text encoded. 

**Workaround:**  editing of the secrets above (data.HARBOR_DATABSE_PASSWORD and data.POSTGRESQL_PASSWORD) and redeploy the exporter, core and jobservice workloads  Then it works and is up & running.  The same behaviour (and errors) with next pipeline run with our terraform-based approach.
