### ISSUE TITLE
Helm Charts Tab missing for Harbor installation with Helm

### ISSUE THREAD

**Issue by MBelkhechine** [goharbor/harbor-helm#1715]
Hi,

I have installed Harbor v2.0 using helm.

I have some trouble setting up and enabling the Helm Charts Tab in harbor.

Is there any parameter which I should change in the `values.yaml` file to enable the Helm Chats Tab next to the repositories in projects? 

Any help is much appreciated.

Thank you.

**Comment by Kajot-dev** [comment]
This is the feature of chartmuseum which was removed in v2.8.0 due to the fact that helm charts can now be pushed via OCI to the same repository as images (and they appear in the repository tab)

See: https://github.com/goharbor/harbor/releases/tag/v2.8.0
How to push helm charts using OCI (to harbor >= 2.8.0): https://helm.sh/docs/topics/registries/
