### ISSUE TITLE
Harbor metrics exporter

### ISSUE THREAD

**Issue by tnubeo1111** [goharbor/harbor-helm#1798]
Hello team, 

Currently I am setting up harbor version 2.11.0 using helm but now I want to enable harbor metrics and transfer metrics to another prometheus server, what should I do? I followed the docs but it still doesn't work

Hope the team can help.

**Comment by Kajot-dev** [comment]
You would need to expose it somehow. Either via separate Ingress (since Ingress only listens on http/s) or via NodePort/Loadbalancer service.

Although sending metric between the clusters does not make much sense to me, escpecially from the security standpoint. It would be much better to for example use Prometheus Operator which provides neat CRD like `ServiceMonitor`, `PrometheusRule` just for that + AlertManager for notifications
