### ISSUE TITLE
OIDC Authentication Issues When Changing .secretKey

### ISSUE THREAD

**Issue by KISStian** [goharbor/harbor-helm#325]
We changed the Harbor "not-a-secret-key" to a custom 16-character value, but noticed issues while trying to authenticate into the portal via OIDC.  A 401 response was received and the core logs stated that it could not fetch the token.  However, we were able to authenticate using the admin credentials.  To resolve the issue, the secret was reverted to the Harbor default.  The issue persisted, but after deleting the core pod, we were able to authenticate once it was recreated.

Should .secretKey in the values file never change?  I expected that Harbor would be able to accommodate a change to this parameter without breaking OIDC authentication.

**Comment by ywk253100** [comment]
The `secretKey` is used to encryption/decryption token and password. Just like mentioned in #326, users need to make sure the `secretKey` isn't changed during the whole lifecycle of Harbor

**Comment by Wortany** [comment]
@ywk253100 Actually I can also confirm that on a fresh helm install where a custom secretKey is specified in the configuration, OIDC is broken.

The OIDC Client Secret does not get decrypted correctly to pass along when the the access token is requested from the OIDC provider, resulting in a 401 Unauthorized response.

**Comment by reasonerjt** [comment]
@Wortany 
I'll try to reproduce this issue.

By `OIDC is broken` could you elaborate what error you are seeing?
Could you provide the logs to help me debug?

**Comment by Wortany** [comment]
Apologies for the vagueness. 
What happens during the OIDC login attempt: (utilising Google for this)
1. Redirect to OIDC Provider (Google) is successful
2. User logs in
3. Google redirects to Harbor callback URL with: state, code, scopes
4. Harbor receives the callback then verifies the state and exchanges the code for an access token from the provider by sending along the received code + client id + client secret.

In the case Harbor is set up with a custom secretKey, the following 401 response is returned from the provider (Google) when Harbor calls the token endpoint:
```
2019-08-22T05:22:59Z [ERROR] [/core/controllers/oidc.go:89]: Failed to exchange token, error: oauth2: cannot fetch token: 401 Unauthorized
Response: {
  "error": "invalid_client",
  "error_description": "Unauthorized"
}
2019-08-22T05:22:59Z [ERROR] [/common/api/base.go:68]: GET /c/oidc/callback?state=dgn533ussh654uv08g6cajvx0on2utc4&code=4/qQEWZQhf6w3EvxlDSPUAdc47zUEy7Scd2kVQl_gNJaqMpJtbudObOU55zg3WQOne4QT69ZwrGGkjVi4sNhAZY5o&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile&authuser=0&hd=diriger.kr&session_state=c68b1551e03274b6e5053b4d7fd6c1c07944b643..a906&prompt=consent failed with error: {"code":400,"message":"oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\n  \"error\": \"invalid_client\",\n  \"error_description\": \"Unauthorized\"\n}"}
2019/08/22 05:22:59 [D] [server.go:2619] | 222.96.152.119| 400 | 525.765506ms|   match| GET      /c/oidc/callback   r:/c/oidc/callback
```

This error is returned by Google's token endpoint when the correct Client ID, Grant, Redirect_uri is provided but an incorrect Client Secret.

If I try to use the code provided by the callback as seen in the logs and do a Post to Google's token endpoint manually (while it was still valid) with the correct Client Secret, it successfully returns a token. 

All of this only happens when installing the Helm Chart with a custom secretKey.
Leave it to the default setting and the OIDC logins are successfully processed.

**Comment by reasonerjt** [comment]
@Wortany so sorry for the late reply,

Please clarify, did you setup Harbor using default secret key and later switch to custom secret key?

My guess is the client secret was encrypted by the old key and you try to decrypt with new key, so it gets the wrong result.

In your env with custom secretkey, could you update the oidc setting, for example and store again, to make sure the client secret is encrypted by the new key?

**Comment by Wortany** [comment]
@reasonerjt My double apologies for taking even longer to reply (completely lost sight of this)

It was not a delayed switch to a new key, my test was deploying a fresh setup (with no prior storage) to kubernetes through helm install

Example:
```
helm install --name "harbor-repository" \
--set secretKey="generated-key" \
harbor/harbor
```

**Comment by sidewinder12s** [comment]
Is there really still no way to update this secretKey?

What is it used for internally to harbor? 

We ran into an outage because we attempted to change this value and while we could re-save the OIDC config, it was not at all clear that was the only thing that the secretKey is used to encrypt.

**Comment by snakebyte91** [comment]
Is there any workaround to change key?

**Comment by Vad1mo** [comment]
> The documentation should **very clearly** highlight that if this secret value changes, it will make your harbor instance largely unusable. This just caught us by surprise and now we had to wipe our DB.

Makes sense.
Where would you have expected it to be written in the docs or chart README?

**Comment by Vad1mo** [comment]
> further: what is odd is that things were still broken even after reverting the secret back to its original value. is that expected?

it probably encrypts with the new key.
