### ISSUE TITLE
Backup Harbor on K8S

### ISSUE THREAD

**Issue by LunaticZorr** [goharbor/harbor-helm#384]
Hello,

We're using Harbor to host multiple registries and we want to back it up at least once a day. What is the best/suggested way of performing a full backup of Harbor including database, users, images, etc?

I can't seem to find anything in the documentation

Thanks!

**Comment by dntosas** [comment]
Maybe a 3rd party software can help you on this rather than Harbor itself.

Check Velero --> https://velero.io/

**Comment by ywk253100** [comment]
@dntosas Agree

**Comment by ragingpastry** [comment]
This is definitely something that needs to be documented for this to be considered a useful product.

**Comment by reasonerjt** [comment]
As pointed out, backing up a chart relies on external tooling, and is highly highly depended on the environment and infrastructure the k8s cluster is running on.

I don't think we can document this in this repo because we can't answer questions of veleros here.

If Harbor is to be bundled with velero as a solution for customers, we should document and support it in the bundled product/solution. 
NOT in this OSS repo.

Closing as a won't fix.

**Comment by ragingpastry** [comment]
I disagree. There should absolutely be documentation on how to back up this Harbor deployment. While Veleros could be useful I think it is the responsibility of this project to document a simple backup method that users could use.

Backing up an application shouldn't really depend on the infrastructure k8s is running on. Take gitlab for example. Gitlab has a built in tool which will perform backups of the Gitlab service and output a bundled tar for users. Harbor should have something similar in my opinion. Backups need to be considered as a first class feature of a project for a project to be considered for real production use-cases. Even a simple backup document would be sufficient.

**Comment by arjunprasad2143** [comment]
True @ragingpastry .I'm also looking for an answer to that question
