### ISSUE TITLE
Goharhor UI: Cannot see the image pushed using Skopeo

### ISSUE THREAD

**Issue by saikirandusari** [goharbor/harbor-helm#44]
Pushed an image goharbor registry using [Skopeo](https://github.com/containers/skopeo) but couldn't see it in GoHarbor UI. 

Note: I'm able to inspect the pushed image to goharbor registry without any issues. 
Command used: 'skopeo inspect IMAGE-NAME' 

Here is the command: 
skopeo --debug copy --src-creds=<token> --dest-creds=<token>  docker://registry-one/project/imageName:latest docker://goharbor-registry/project/imageName:latest

skopeo version 0.1.26

**Comment by reasonerjt** [comment]
This issue is not about the helm but harbor itself, please open it in the repo
https://github.com/goharbor/harbor

As this particular problem you are seeing, we use a white list in notification handler so the skopeo is filtered out.

This essentially is a dup to https://github.com/goharbor/harbor/issues/5729

**Comment by reasonerjt** [comment]
Hence, I'm closing this issue.
