### ISSUE TITLE
If persistence=true, the storage volumeMount has incorrect owner:group

### ISSUE THREAD

**Issue by dankirkpatrick** [goharbor/harbor-helm#486]
If persistence is turned on, the registry deployment mounts the /storage volumeMount with the incorrect owner.

To fix the issue I added an initContainer to the deployment to set the owner/group to 10000:10000.  It looks like this:

>       initContainers:
>       - command:
>         - sh
>         - -c
>         - chown -R 10000:10000 /storage
>         image: busybox
>         imagePullPolicy: Always
>         name: volume-mount-hack
>         resources: {}
>         terminationMessagePath: /dev/termination-log
>         terminationMessagePolicy: File
>         volumeMounts:
>         - mountPath: /storage
>           name: registry-data

**Comment by ywk253100** [comment]
The permission issue should be covered by security context: https://github.com/goharbor/harbor-helm/blob/master/templates/registry/registry-dpl.yaml#L34

**Comment by reasonerjt** [comment]
@dankirkpatrick 
Could you double check it `fsGroup` is supported by your env?

**Comment by huats** [comment]
I am facing the same issue both for the registry and redis. And the fsGroup apparently does not enforce the needed permissions on some case (like mine using NFS with rook and it seems I am not the only one https://github.com/kubernetes/examples/issues/260)
I have created a pull request that fixes that, and that is a bit more evolved than the simple code put by @dankirkpatrick  since I use the same template mechanism used by the database pod/statefulset. #647
