### ISSUE TITLE
Trivy replicas > 1, is it an improvement ?

### ISSUE THREAD

**Issue by gunboe** [goharbor/harbor-helm#503]
I'd like to make a Cluster with more than one Clair, for example. 
Is it possible? 
Is there some issue that I could work around?

~Indeed I have a Harbor Cluster with a Load Balancer forwarding to 2 Harbor instances but a only one Postgress DB and one Registry Ceph Storage. Everything is running perfectly, although I do not schedulle a Clair Scanning cause I will have 2 Clair instaces running at same time doing the same work, it doesn't look good. So my thought is stop one of them. Any idea?~

Thanks all!

**Comment by gunboe** [comment]
So let me update this issue, now I have a Harbor/Helm v2.2.2 installed in Kubernetes Cluster with Trivy Scanner and Redis installed by Helm Chart, and the artifacts stored in S3/Ceph Cluster and the PostgreSQL is external.

The Harbor works fine, but I have 55K artifacts and all scanning process with only 1 Trivy replica spent 11 hours to finish and in practice increasing replicas does not decrease the time like could I thought. I have increased Trivy replicas to 6 but the time was the same 11 hours.

In theory increase Trivy replicas should improve scan time, doesn't it? How many replicas deal with scan jobs? Is there a kind of queue so Trivy run in parallel? 

tks

**Comment by JorenZ** [comment]
With apologies for the thread necro: I just noticed that increasing the number of jobservice replicas _does_ scale the number of concurrent scans, whereas just increasing the number of Trivy replicas by itself does not do so.
I seem to notice 10 concurrent jobs per jobservice instance (currently: 8 instances gives us 80 concurrent scans).
I've updated the number of Trivy replicas to match (currently: 8 instances, presumably receiving ~10 scans each but I'm not even sure it works like that).

Since Trivy scans are performed as Harbor jobs via the job service under the hood, I guess this makes sense.
I could not find it in the documentation however.
