### ISSUE TITLE
Wrong redirect if deployed behind external proxy

### ISSUE THREAD

**Issue by lz006** [goharbor/harbor-helm#536]
If harbor is deployed behind external proxy, setting **externalURL** isn't enough. 

When docker establishes a connection to harbor it first gets a http 301. But **location** header of this response wrongly contains address defined in **ingress.hosts.core**, which is typically not accessible in such a reverse proxy scenario.

We couldn't find any flag that controls this behavior, so we had to fix this at reverse proxy site by using following haproxy config:

http-response replace-header Location http(s?):\\/\\/(.\*?)\\/(.\*) <EXTERNAL_URL>/\\3

It might help someone out.

We experienced this problem using 

**harbor-helm**
**version v1.3**

https://github.com/goharbor/harbor/issues/11100

**Comment by reasonerjt** [comment]
Could you reproduce the issue with a `curl` command to help us better understand?

Looks like the header was added by ingress controller?

**Comment by lz006** [comment]
Setup: client -> reverse proxy (haproxy) -> k8s ingress (nginx) -> harbor core

With header replacement at reverse proxy:
``` bash 
curl <EXTERNAL_URL>/v2 -vvv 
# gives:
#HTTP/1.1 301 Moved Permanently
#...
#content-type: text/html
#content-length: 175
#location: <EXTERNAL_URL>/v2/
```
**Without** header replacement at reverse proxy:
``` bash 
curl <EXTERNAL_URL>/v2 -vvv 
# gives:
# HTTP/1.1 301 Moved Permanently
#...
#content-type: text/html
#content-length: 175
#location: <INGRESS_HOST_OF_HARBOR_CORE>/v2/
```

**Comment by lylex** [comment]
I am running into the same issue.
And a tiny difference, I am setting up harbor behind nginx, with does the tls termination, and reaches harbor via "https://lab.mycompany.com/harbor/v2", etc, and I disabled tls in harbor. But the redirects come from harbor goes to something like "https://lab.mycompany.com/light-theme.css", which ignores the '/harbor' prefix.

**Comment by GCHQDeveloper0985** [comment]
I'm also having a similar issue to this. I'm running Harbor behind a nginx reverse proxy. We have multiple services behind this proxy, so Harbor is accessed at https://nginxdomain.com/harbor and other services are accessed at https://nginxdomain.com/prometheus etc. I've configured the `externalURL` to be https://nginxdomain.com/harbor (tried with both goharbor/helm-charts and the bitnami/harbor chart) and the UI doesn't display properly as @lylex says. 

When accessing the UI at https://nginxdomain.com/harbor, the `index.html` page loads and I see `Loading...`, but Chrome 404s when trying to retrieve the CSS and JS as it ignores the subpath. Instead of getting them from https://nginxdomain.com/harbor/light-theme.css, it tries to get the resources from https://nginxdomain.com/light-theme.css.

I've had a look at the [source](https://github.com/goharbor/harbor/blob/master/src/portal/src/index.html#L7) and it looks like the base href in `index.html` is set to `/` so all other refs are taking a relative path from there. For example, Grafana have a [configurable base href](https://github.com/grafana/grafana/blob/b3b28e9f25955ea6e160c1f384b1ebad5190e459/public/views/index-template.html#L24)

I'm happy to try and fix this issue if you're able to point me in the right direction :smiley: 

Thanks!

**Comment by csikosbalint** [comment]
Facing the same issue. Do you have any fix or workaround?

**Comment by GCHQDeveloper0985** [comment]
@csikosbalint It was a long time ago now but I believe we changed our NGINX config to rewrite the base href in `index.html` so that it included the sub path that we wanted. Not a great solution but it got us around the problem at the time.
