### ISSUE TITLE
pull based azure replication failed on AKS

### ISSUE THREAD

**Issue by Balador59** [goharbor/harbor-helm#612]
Hi, i just deployed a fresh version of harbor 2.0.0 on AKS and i have two issues :
1. when i add a azure registry with https i have a ping fail, if i use http it work :
![image](https://user-images.githubusercontent.com/26925277/83934251-ce458780-a7af-11ea-8f9c-c0c7b9c9323e.png)

![image](https://user-images.githubusercontent.com/26925277/83934257-e6b5a200-a7af-11ea-837a-1d6a2679adc9.png)

2. when i want to make a replication pull based, it fail : 
![image](https://user-images.githubusercontent.com/26925277/83934321-5f1c6300-a7b0-11ea-9cfa-cc05d468083a.png)

The error :
```bash
2020-06-06T02:34:14Z [ERROR] [/replication/operation/controller.go:108]: the execution 4 failed: failed to fetch artifacts: invalid character '<' looking for beginning of value

```

I have try to make a fresh installation on a GKE cluster, and i don't have any issues.
Can you help me to troubleshoot this issue ?

**Comment by reasonerjt** [comment]
@Balador59 the ping failure is probably due to certificate verification, could you check the log of `core` when you failed to ping?  If you uncheck the checkbox to make sure Harbor will not verify the cert when pinging the remote registry, will the ping succeed?

The second error is because azure returned some error page, this may be due to you are accessing using HTTP not HTTPS.

**Comment by FrenchBen** [comment]
Running into a similar issue with certification unchecked, I cannot seem to trigger "pull base" replication:
```
[ERROR] [/replication/operation/controller.go:103]: the execution 2 failed: failed to fetch artifacts: invalid character '<' looking for beginning of value
```

**Comment by Danielkem** [comment]
At first I also got the error: `failed to fetch artifacts: invalid character '<' looking for beginning of value`

It turns out that I needed to supply correct credentials in Harbor registries. Meaning creating a Token in ACR, set a scope map (I chose admin) and generate a Password. I also specify `https` and not `http` for the registry in Harbor for the parameter `Endpoint URL`. Now it is working as expected with pull base replication.
