### ISSUE TITLE
Make mounting of service account token configurable

### ISSUE THREAD

**Issue by LinAnt** [goharbor/harbor-helm#887]
As the title suggests I think the automounting of service account tokens should be configurable.

We use bankvaults for managing all harbor secrets, and thus we need the service account token to be able to fetch the secrets from vault.

A pr with the suggested fix can be found here https://github.com/goharbor/harbor-helm/pull/886

Best regards, LinAnt

**Comment by mumrau** [comment]
I was about to write what you just did (including the PR) yesterday and postponed it to today (due to permissions directory issue on harbor database)! 
I'm glad you just did and I truly believe this is much needed. I really like the fact that this chart tries to keep up with wecurity recommandation (working under PsP, not automounting token, etc...), but I also think we should make most field tweakable so that users with various (common) needs can keep a self-supporting `values.yaml` file.  (Same philosophy as https://github.com/goharbor/harbor-helm/issues/876#issuecomment-793528546).

I upvote this issue and the associated PR!

**Comment by ywk253100** [comment]
Fixed by #886
