### ISSUE TITLE
Harbor DB not coming Up on upgrade / fresh installation 

### ISSUE THREAD

**Issue by mohitsharma-in** [goharbor/harbor-helm#899]
Harbor DB/ Postgres not coming from helm chart on restricted namespace i.e with limit ranges defined since init container doesn't have and resources defined.

Can we include the same resource definition for Init containers also which we are using for container

**Comment by reasonerjt** [comment]
Could you provide more information regarding " restricted namespace"?

**Comment by mohit94614** [comment]
Restricted namespace in the sense namespace with resource quota and the custom role and role binding.
what we observed was the Postgres ie harbor DB was not having a resource definition for the INIT container. Since we restrict all the deployment in our namespace to have resource defined the DB pod was not coming up 


Fix :

We added below to init container and  post that DB container came up 
```
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:        100m
      memory:     256Mi
```


Do let me Know if further detail is required.
