### ISSUE TITLE
exposing registry part only privately

### ISSUE THREAD

**Issue by fragolinux** [goharbor/harbor-helm#990]
hi, i just set up harbor using this chart, it seems to work flawlessly :D

i added to my cluster an imageswap automation to redirect image pulls to harbor, using a robot account and a private caching project, i can deploy something and it will ask harbor for the image and if it has not the image already downloaded, will download and give to my cluster (need to figure it out how to add the imagepullsecret automatically to manifests, work for afternoon...)

problem is: now my harbor is exposed on internet, and all endpoints are using the same fqdn, on AWS and so using ALB as load balancer... so, each image i pull from INSIDE the cluster, causes traffic as doing the "external" path, through ALB, to retrieve it...

is there a way, and eventually how, to expose the management part on the public front, and have the images available only from inside the cluster? How to modify the chart?

or, better, how to have a double path, so i can in any case have my images and charts available from the internet, but have my cluster download them internally, without passing through the external LB?

just to avoid useless (and paid) routes to the data, and add even more security: on a side note, is there a way to disable normal login and leave only the OIDC one i already set up and fully working?

thanks in advance, best regards

**Comment by reasonerjt** [comment]
@fragolinux 
I see there are more than one questions in this issue:

1) The helm chart or any installation that Harbor community supports, they only support exposing Harbor in one way.  That said, if you look into the implementation, it should be possible to setup another `harbore-core` container facing the internal only, and make it share the DB and registry, it involves a bunch of manual steps and customizations, you should also make sure the internal facing `harbore-core` is pull-only by setting up a reverse proxy and disable some of the APIs, I think it's do-able but there's no doc about that.

By reading the OP I also don't quite understand your use case, it seems you don't need to expose your Harbor instance to the internet, because all the requests are from internal?

2) ` is there a way to disable normal login and leave only the OIDC one i already set up and fully working?`  Could you explain why you need normal login?  If you set Harbor to OIDC auth mode, except for the `admin` user, all users have to go through OIDC

**Comment by fragolinux** [comment]
hi! And thanks for the answer :)
1. yes, we only need to make harbor available from internal, how can core and portal be split so the management gui be accessed over internet, and the core only from internal? That's not clear to me...
2. oh, understood, ok, so we'll put a string password on admin and use normal oidc users for day by day maintenance...
thanks!
